---
apiVersion: v1
kind: Service
metadata:
  name: mutateme
  labels:
    app: mutateme
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: mutateme

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutateme
  labels:
    app: mutateme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutateme
  template:
    metadata:
      name: mutateme
      labels:
        app: mutateme
    spec:
      containers:
        - name: mutator
          image: ttl.sh/b08c0ba4-dc04-46c5-b255-42fbe68b5cf9:1h
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutateme
  labels:
    app: mutateme
webhooks:
  - name: mutateme.default.svc.cluster.local
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTWpRME56TXlNRFV3SGhjTk1qUXdPREkwTURReU1EQTFXaGNOTXpRd09ESXlNRFF5TURBMQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTWpRME56TXlNRFV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUWlgrSFRVeFpzMmc0TVc2MTRleHIyazdyZGx0SmdWOWhSYkhGQllBYXgKU3NEUjNUeDZEU3UzL2pPN1VWOUkxNHJzTnFDdG1PTldIS3BJU3p3dWNnemJvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVhzSDBqUHFWUktsM0trb2cwRG1LCkRDSlNZRFF3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnQlA1ZFhMdDRIdG5kS3VtVmFFNWtDTlNwb0V2eE15eFcKNldabllEQWVLVllDSVFESWM5QkhMVTRPdVdycTBFb0lQRFhKRHdyVnFzYlEvcERCcG9tQythN1E3UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: mutateme
        namespace: default
        path: "/mutate"
        port: 443
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    admissionReviewVersions: ["v1"]
    timeoutSeconds: 5
    reinvocationPolicy: Never
    failurePolicy: Ignore
    namespaceSelector:
      matchLabels:
        mutateme: enabled
